baseURL = "https://rootimes.github.io/my-logs/"
title = "Rootimes's Code ICU"
copyright = "Rootimes"
pagerSize = 5
languageCode = "zh-TW"
defaultContentLanguage = "zh-TW"
theme = "hugo-theme-tailwind"

[markup]
_merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"