# SEO keywords and description for your site.
keywords = "rootimes's code blog"
subtitle = "rootimes's code icu"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

[header]
  logo = "images/rootimes.webp"

[footer]
  since = 2024
  poweredby = false

[giscus]
    enabled = true
    repo = "rootimes/my-logs"
    repoID = "851189860"
    category = "General"
    categoryID = "DIC_kwDOMrwgZM4CiJxa"
    inputPosition = "bottom"
    reactionsEnabled = "1"

[social_media]
    [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/rootimes'