# SEO keywords and description for your site.
keywords = "rootimes's code blog"
subtitle = "rootimes's code icu"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
toc = false

showReadingTime = true

# use structure json-ld for articles
jsonLD = true

showAuthor = true

[author]
  name = "Rootimes"
  email = "leo32095@gmail.com"

[search]
  summaryInclude = 180 # show only part of content in search result.
  minMatchCharLength = 2 # https://www.fusejs.io/api/options.html#minmatchcharlength
  threshold = 0.3 # https://www.fusejs.io/api/options.html#threshold

[header]
  logo = "images/rootimes.webp"

[footer]
  since = 2024
  poweredby = false

[giscus]
    enabled = true
    repo = "rootimes/my-logs"
    repoID = "R_kgDOMrwgZA"
    category = "General"
    categoryID = "DIC_kwDOMrwgZM4CiJxa"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"

[social_media]
    [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/rootimes'

[sidebar]
  limit = 10

[taxonomies.icons]
  categories = "category-2"
  tags = "hash"
  series = "bookmark"
