baseURL = "http://localhost:1313"
title = "Rootimes's Code ICU"
author = "rootimes"
copyright = "rootimes"
pagerSize = 10
languageCode = "zh-TW"
defaultContentLanguage = "en"
theme = "hugo-theme-tailwind"

[markup]
  _merge = "deep"

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 0

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
