[en]
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 2
  [en.menu]
  [[en.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 1

  [[en.menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "posts"
    weight = 2


[zh-tw]
  languageCode = 'zh-TW'
  languageDirection = 'ltr'
  languageName = '繁體中文'
  weight = 1
  [zh-tw.menu]
  [[zh-tw.menu.main]]
    identifier = "about"
    name = "關於"
    pageRef = "about"
    weight = 1

  [[zh-tw.menu.main]]
    identifier = "post"
    name = "文章"
    pageRef = "posts"
    weight = 2